import { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Copy, Check } from 'lucide-react';
import { matInverse, matDet, matEigenvalues, gaussSolve, fmt, type Matrix, type Vector } from '@/lib/matrix-math';
import { useToast } from '@/hooks/use-toast';

// ── MATLAB Script Generator ───────────────────────────────────────────────────

type ScriptType = 'bode' | 'fft' | 'nodal' | 'convolution';

const SCRIPT_OPTIONS: { id: ScriptType; label: string; desc: string }[] = [
  { id: 'bode',        label: 'Bode Plot',       desc: 'Frequency response of a transfer function' },
  { id: 'fft',         label: 'FFT Analysis',     desc: 'Single-sided amplitude spectrum of a signal' },
  { id: 'nodal',       label: 'Nodal Analysis',   desc: 'Solve Y·V = I for node voltages' },
  { id: 'convolution', label: 'Convolution',      desc: 'Discrete convolution of two signals (f * g)[n]' },
];

function generateScript(type: ScriptType, params: Record<string, string>): string {
  switch (type) {
    case 'bode': return `% ─────────────────────────────────────────────────────
% Bode Plot  |  Generated by ElectroLab Suite
% Transfer function H(s) = num(s) / den(s)
% ─────────────────────────────────────────────────────
clear; clc; close all;

% Numerator and denominator polynomial coefficients
% (highest power first, e.g. s² + 3s + 2  → [1 3 2])
num = [${params.num || '1'}];
den = [${params.den || '1 2 1'}];

sys = tf(num, den);
disp(sys);

% Bode plot
figure('Name', 'Bode Plot', 'NumberTitle', 'off');
bode(sys);
grid on;
title('Bode Magnitude & Phase');

% Stability margins
[Gm, Pm, Wcg, Wcp] = margin(sys);
fprintf('\\nGain  Margin : %.3f dB  (at %.2f rad/s)\\n', 20*log10(Gm), Wcg);
fprintf('Phase Margin : %.2f deg  (at %.2f rad/s)\\n', Pm, Wcp);
`;

    case 'fft': return `% ─────────────────────────────────────────────────────
% FFT Analysis  |  Generated by ElectroLab Suite
% ─────────────────────────────────────────────────────
clear; clc; close all;

fs = ${params.fs || '1000'};           % Sampling frequency (Hz)
N  = ${params.N  || '1024'};           % Number of samples
T  = 1/fs;                              % Sampling period (s)
t  = (0:N-1)*T;                         % Time vector
f  = (0:N/2-1)*(fs/N);                 % One-sided frequency vector (Hz)

% ── Signal definition ──────────────────────────────
% Customize: add sinusoids with desired frequencies & amplitudes
f1 = ${params.f1 || '50'};  A1 = ${params.A1 || '1'};
f2 = ${params.f2 || '150'}; A2 = ${params.A2 || '0.5'};
signal = A1*sin(2*pi*f1*t) + A2*sin(2*pi*f2*t);

% ── FFT computation ────────────────────────────────
Y  = fft(signal, N);
P2 = abs(Y / N);
P1 = P2(1:N/2);
P1(2:end) = 2*P1(2:end);   % Convert double-sided → single-sided

% ── Plots ─────────────────────────────────────────
figure('Name', 'FFT Analysis', 'NumberTitle', 'off');
subplot(2,1,1);
  plot(t, signal, 'b-', 'LineWidth', 1.2);
  xlabel('Time (s)'); ylabel('Amplitude');
  title('Time-Domain Signal'); grid on;

subplot(2,1,2);
  plot(f, P1, 'r-', 'LineWidth', 1.5);
  xlabel('Frequency (Hz)'); ylabel('|X(f)|');
  title('Single-Sided Amplitude Spectrum'); grid on;
`;

    case 'nodal': return `% ─────────────────────────────────────────────────────
% Nodal Analysis  (Y·V = I)  |  Generated by ElectroLab Suite
% ─────────────────────────────────────────────────────
clear; clc;

% Nodal admittance matrix  Y  [Siemens]
% Rows/columns correspond to independent nodes (ground excluded).
% Fill in conductances: diagonal = sum of branch admittances at node,
%                       off-diag = −admittance between nodes i and j.
Y = [${params.Y || '0.15 -0.05; -0.05 0.07'}];

% Independent current sources entering each node  I  [Amperes]
I = [${params.I || '0.1; 0'}]';
I = I(:);   % ensure column vector

% ── Solve ─────────────────────────────────────────
if det(Y) == 0
    error('Admittance matrix is singular — check your circuit.');
end
V = Y \\ I;

% ── Display results ────────────────────────────────
fprintf('\\n=== Node Voltages ===\\n');
for k = 1:length(V)
    fprintf('  V%d = %+.6f V\\n', k, V(k));
end

% Branch currents (between nodes i and j via admittance Yij)
% Example: I_12 = (V(1) - V(2)) * Y(1,2)  [edit as needed]
`;

    case 'convolution': return `% ─────────────────────────────────────────────────────
% Discrete Convolution  (f * g)[n]  |  Generated by ElectroLab Suite
% ─────────────────────────────────────────────────────
clear; clc; close all;

% ── Signal definitions ─────────────────────────────
f = [${params.f || '1 1 1 1 1'}];          % Signal f[n]
g = [${params.g || '1 0.8 0.6 0.4 0.2'}]; % Signal g[n]

% ── Convolution ────────────────────────────────────
y = conv(f, g);                            % Linear convolution
n_f = 0:length(f)-1;
n_g = 0:length(g)-1;
n_y = 0:length(y)-1;

% ── Plots ─────────────────────────────────────────
figure('Name', 'Convolution (f * g)[n]', 'NumberTitle', 'off');
subplot(3,1,1);
  stem(n_f, f, 'filled', 'b', 'LineWidth', 1.2);
  title('f[n]'); xlabel('n'); ylabel('f[n]'); grid on;

subplot(3,1,2);
  stem(n_g, g, 'filled', 'r', 'LineWidth', 1.2);
  title('g[n]'); xlabel('n'); ylabel('g[n]'); grid on;

subplot(3,1,3);
  stem(n_y, y, 'filled', 'k', 'LineWidth', 1.5);
  title('(f * g)[n]  — Convolution Result');
  xlabel('n'); ylabel('(f*g)[n]'); grid on;

fprintf('Output length: %d samples\\n', length(y));
`;
  }
}

function ParamInput({ label, value, onChange, placeholder }:
  { label: string; value: string; onChange: (v: string) => void; placeholder?: string }) {
  return (
    <div>
      <Label className="text-xs text-muted-foreground mb-1 block">{label}</Label>
      <Input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}
        className="font-mono bg-background border-border text-sm" />
    </div>
  );
}

export function MATLABScriptGenerator() {
  const [scriptType, setScriptType] = useState<ScriptType>('bode');
  const [params, setParams] = useState<Record<string, string>>({
    num: '1', den: '1 3 2',
    fs: '1000', N: '1024', f1: '50', A1: '1', f2: '150', A2: '0.5',
    Y: '0.15 -0.05; -0.05 0.07', I: '0.1 0',
    f: '1 1 1 1 1', g: '1 0.8 0.6 0.4 0.2',
  });

  const setParam = (key: string, v: string) => setParams(p => ({ ...p, [key]: v }));

  const script = useMemo(() => generateScript(scriptType, params), [scriptType, params]);
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(script).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast({ title: '✓ Copied to clipboard!', description: 'MATLAB script ready to paste', duration: 2500 });
    });
  };

  return (
    <div className="space-y-6">
      {/* Script type selector */}
      <Card className="bg-card border-border">
        <CardHeader className="pb-3">
          <CardTitle className="text-base font-semibold">Select Script Template</CardTitle>
          <CardDescription>Configure parameters, then copy the generated MATLAB / GNU Octave code</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            {SCRIPT_OPTIONS.map(o => (
              <button key={o.id} onClick={() => setScriptType(o.id)}
                className={`p-3 rounded-lg border text-left transition-all ${
                  scriptType === o.id
                    ? 'bg-primary/10 border-primary/50 text-primary'
                    : 'bg-muted/20 border-border text-muted-foreground hover:border-primary/30 hover:text-foreground'
                }`}>
                <div className="text-sm font-semibold">{o.label}</div>
                <div className="text-xs opacity-70 mt-0.5">{o.desc}</div>
              </button>
            ))}
          </div>

          {/* Parameters per script type */}
          <div className="pt-2 border-t border-border">
            <p className="text-xs text-muted-foreground mb-3 font-mono uppercase tracking-wide">Parameters</p>
            {scriptType === 'bode' && (
              <div className="grid grid-cols-2 gap-4">
                <ParamInput label="Numerator coefficients" value={params.num} onChange={v => setParam('num', v)} placeholder="1" />
                <ParamInput label="Denominator coefficients" value={params.den} onChange={v => setParam('den', v)} placeholder="1 3 2" />
              </div>
            )}
            {scriptType === 'fft' && (
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
                <ParamInput label="Sampling frequency (Hz)" value={params.fs} onChange={v => setParam('fs', v)} placeholder="1000" />
                <ParamInput label="N samples" value={params.N} onChange={v => setParam('N', v)} placeholder="1024" />
                <ParamInput label="Freq f1 (Hz)" value={params.f1} onChange={v => setParam('f1', v)} placeholder="50" />
                <ParamInput label="Amplitude A1" value={params.A1} onChange={v => setParam('A1', v)} placeholder="1" />
                <ParamInput label="Freq f2 (Hz)" value={params.f2} onChange={v => setParam('f2', v)} placeholder="150" />
                <ParamInput label="Amplitude A2" value={params.A2} onChange={v => setParam('A2', v)} placeholder="0.5" />
              </div>
            )}
            {scriptType === 'nodal' && (
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <ParamInput label="Y matrix (rows separated by ';')" value={params.Y} onChange={v => setParam('Y', v)} placeholder="0.15 -0.05; -0.05 0.07" />
                <ParamInput label="I vector (space-separated)" value={params.I} onChange={v => setParam('I', v)} placeholder="0.1 0" />
              </div>
            )}
            {scriptType === 'convolution' && (
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <ParamInput label="Signal f[n] (space-separated)" value={params.f} onChange={v => setParam('f', v)} placeholder="1 1 1 1 1" />
                <ParamInput label="Signal g[n] (space-separated)" value={params.g} onChange={v => setParam('g', v)} placeholder="1 0.8 0.6 0.4 0.2" />
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Generated code */}
      <Card className="bg-card border-border">
        <CardHeader className="pb-2 flex-row items-center justify-between">
          <div>
            <CardTitle className="text-sm font-semibold">Generated Code</CardTitle>
            <CardDescription className="text-xs">Compatible with MATLAB R2016b+ and GNU Octave 6+</CardDescription>
          </div>
          <button onClick={copy}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-border bg-muted/20 hover:bg-muted/50 text-xs font-mono text-muted-foreground hover:text-foreground transition-colors">
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
        </CardHeader>
        <CardContent className="p-0">
          <pre className="text-xs font-mono text-foreground/85 bg-muted/10 p-4 rounded-b-lg overflow-x-auto leading-relaxed whitespace-pre">
            {script}
          </pre>
        </CardContent>
      </Card>
    </div>
  );
}

// ── EE Matrix Calculator ──────────────────────────────────────────────────────

type MatOp = 'inverse' | 'det' | 'eigen' | 'solve';
type MatResult =
  | { op: 'inverse'; inv: Matrix; det: number }
  | { op: 'det'; det: number }
  | { op: 'eigen'; values: number[] }
  | { op: 'solve'; x: Vector; det: number }
  | { op: 'error'; message: string };

const MAT_OPS: { id: MatOp; label: string }[] = [
  { id: 'det',     label: 'Determinant  |A|' },
  { id: 'inverse', label: 'Inverse  A⁻¹' },
  { id: 'eigen',   label: 'Eigenvalues  λ' },
  { id: 'solve',   label: 'Solve  Ax = b' },
];

function MatrixGrid({ n, values, onChange, label }: {
  n: number; values: string[][]; onChange: (v: string[][]) => void; label?: string;
}) {
  return (
    <div>
      {label && <Label className="text-xs text-muted-foreground mb-2 block">{label}</Label>}
      <div className="inline-grid gap-1" style={{ gridTemplateColumns: `repeat(${n}, minmax(0, 1fr))` }}>
        {Array.from({ length: n }, (_, i) =>
          Array.from({ length: n }, (_, j) => (
            <Input key={`${i}-${j}`} type="number" step="any"
              value={values[i]?.[j] ?? '0'}
              onChange={e => {
                const nv = values.map(r => [...r]);
                nv[i][j] = e.target.value;
                onChange(nv);
              }}
              className="font-mono text-center text-sm p-1 h-9 w-16 bg-background border-border"
            />
          ))
        )}
      </div>
    </div>
  );
}

function makeEmpty(n: number): string[][] {
  return Array.from({ length: n }, (_, i) =>
    Array.from({ length: n }, (_, j) => (i === j ? '1' : '0')));
}

function ResultMatrix({ mat }: { mat: Matrix }) {
  return (
    <div className="inline-grid gap-1" style={{ gridTemplateColumns: `repeat(${mat[0].length}, minmax(0, 1fr))` }}>
      {mat.flatMap((row, i) => row.map((v, j) => (
        <div key={`${i}-${j}`}
          className="font-mono text-xs text-primary text-center bg-primary/5 border border-primary/20 rounded px-2 py-1.5 min-w-[56px]">
          {fmt(v)}
        </div>
      )))}
    </div>
  );
}

export function MatrixCalculator() {
  const [size, setSize] = useState(3);
  const [aVals, setAVals] = useState<string[][]>(() => makeEmpty(3));
  const [bVals, setBVals] = useState<string[]>(() => Array(3).fill('0'));
  const [activeOp, setActiveOp] = useState<MatOp>('det');
  const [result, setResult] = useState<MatResult | null>(null);

  const changeSize = (n: number) => {
    setSize(n);
    setAVals(makeEmpty(n));
    setBVals(Array(n).fill('0'));
    setResult(null);
  };

  const parseMatrix = (): Matrix | null => {
    const m = aVals.map(row => row.map(Number));
    if (m.some(row => row.some(isNaN))) return null;
    return m;
  };

  const calculate = () => {
    const A = parseMatrix();
    if (!A) { setResult({ op: 'error', message: 'Invalid matrix entries.' }); return; }

    if (activeOp === 'det') {
      setResult({ op: 'det', det: matDet(A) });
    } else if (activeOp === 'inverse') {
      const r = matInverse(A);
      if (!r) { setResult({ op: 'error', message: 'Matrix is singular — no inverse exists.' }); return; }
      setResult({ op: 'inverse', inv: r.inv, det: r.det });
    } else if (activeOp === 'eigen') {
      const vals = matEigenvalues(A);
      setResult({ op: 'eigen', values: vals });
    } else {
      const b: Vector = bVals.map(Number);
      if (b.some(isNaN)) { setResult({ op: 'error', message: 'Invalid b vector entries.' }); return; }
      const r = gaussSolve(A, b);
      if (!r) { setResult({ op: 'error', message: 'System is singular — no unique solution.' }); return; }
      setResult({ op: 'solve', x: r.x, det: r.det });
    }
  };

  return (
    <div className="space-y-6">
      <Card className="bg-card border-border">
        <CardHeader className="pb-3">
          <CardTitle className="text-base font-semibold">Matrix Input</CardTitle>
          <CardDescription>Enter the N×N matrix A (and vector b for Ax = b). Ideal for mesh / nodal analysis.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          {/* Size selector */}
          <div>
            <Label className="text-xs text-muted-foreground mb-2 block">Matrix Size</Label>
            <div className="flex gap-2">
              {[2, 3, 4, 5].map(n => (
                <button key={n} onClick={() => changeSize(n)}
                  className={`px-3 py-1.5 rounded-md text-sm font-mono font-medium transition-colors border ${
                    size === n
                      ? 'bg-primary/20 text-primary border-primary/50'
                      : 'bg-muted/30 text-muted-foreground border-border hover:border-primary/30'
                  }`}>
                  {n}×{n}
                </button>
              ))}
            </div>
          </div>

          {/* Matrix A */}
          <div className="space-y-2">
            <Label className="text-xs text-muted-foreground block">Matrix A</Label>
            <div className="overflow-x-auto">
              <MatrixGrid n={size} values={aVals} onChange={setAVals} />
            </div>
          </div>

          {/* Vector b (only for solve) */}
          {activeOp === 'solve' && (
            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground block">Vector b (right-hand side)</Label>
              <div className="flex gap-1">
                {bVals.map((v, i) => (
                  <Input key={i} type="number" step="any" value={v}
                    onChange={e => {
                      const nv = [...bVals]; nv[i] = e.target.value; setBVals(nv);
                    }}
                    className="font-mono text-center text-sm p-1 h-9 w-16 bg-background border-border"
                  />
                ))}
              </div>
            </div>
          )}

          {/* Operation + Calculate */}
          <div className="space-y-3 pt-1 border-t border-border">
            <div className="flex gap-2 flex-wrap">
              {MAT_OPS.map(op => (
                <button key={op.id} onClick={() => { setActiveOp(op.id); setResult(null); }}
                  className={`px-3 py-1.5 rounded-md text-xs font-mono font-medium transition-colors border ${
                    activeOp === op.id
                      ? 'bg-primary/20 text-primary border-primary/50'
                      : 'bg-muted/30 text-muted-foreground border-border hover:border-primary/30'
                  }`}>
                  {op.label}
                </button>
              ))}
            </div>
            <button onClick={calculate}
              className="px-5 py-2 bg-primary/20 text-primary border border-primary/50 rounded-md text-sm font-mono font-semibold hover:bg-primary/30 transition-colors">
              Calculate →
            </button>
          </div>
        </CardContent>
      </Card>

      {/* Result display */}
      {result && (
        <Card className={`border-border ${result.op === 'error' ? 'bg-red-500/5 border-red-500/30' : 'bg-card'}`}>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold">
              {result.op === 'error' ? 'Error' : 'Result'}
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {result.op === 'error' && (
              <p className="text-red-400 font-mono text-sm">{result.message}</p>
            )}
            {result.op === 'det' && (
              <div>
                <p className="text-xs text-muted-foreground mb-1 font-mono">det(A)</p>
                <p className="text-2xl font-mono font-bold text-primary">{fmt(result.det)}</p>
                {Math.abs(result.det) < 1e-10 && (
                  <p className="text-xs text-amber-400 mt-1 font-mono">Matrix is singular (det ≈ 0)</p>
                )}
              </div>
            )}
            {result.op === 'inverse' && (
              <div className="space-y-3">
                <div>
                  <p className="text-xs text-muted-foreground mb-2 font-mono">A⁻¹</p>
                  <div className="overflow-x-auto"><ResultMatrix mat={result.inv} /></div>
                </div>
                <p className="text-xs font-mono text-muted-foreground">det(A) = {fmt(result.det)}</p>
              </div>
            )}
            {result.op === 'eigen' && (
              <div>
                <p className="text-xs text-muted-foreground mb-2 font-mono">Eigenvalues λ (sorted)</p>
                <div className="flex flex-wrap gap-2">
                  {[...result.values].sort((a, b) => b - a).map((v, i) => (
                    <div key={i} className="font-mono text-sm px-3 py-1.5 bg-primary/10 text-primary border border-primary/30 rounded">
                      λ{i + 1} = {fmt(v)}
                    </div>
                  ))}
                </div>
                <p className="text-xs font-mono text-muted-foreground mt-2">Best for symmetric matrices (admittance / impedance). Non-symmetric may show approximations.</p>
              </div>
            )}
            {result.op === 'solve' && (
              <div className="space-y-3">
                <p className="text-xs text-muted-foreground font-mono">Solution vector x  (Ax = b)</p>
                <div className="flex flex-wrap gap-2">
                  {result.x.map((v, i) => (
                    <div key={i} className="font-mono text-sm px-3 py-1.5 bg-primary/10 text-primary border border-primary/30 rounded">
                      x{i + 1} = {fmt(v)}
                    </div>
                  ))}
                </div>
                <p className="text-xs font-mono text-muted-foreground">det(A) = {fmt(result.det)}</p>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      <Card className="bg-muted/20 border-border">
        <CardHeader className="pb-2">
          <CardTitle className="text-xs font-mono text-muted-foreground uppercase tracking-wider">Nodal / Mesh Analysis Tips</CardTitle>
        </CardHeader>
        <CardContent className="text-xs font-mono text-muted-foreground space-y-1">
          <p>Nodal:   Y·V = I_src  →  use Solve Ax=b (A=Y, b=I)</p>
          <p>Mesh:    Z·I = V_src  →  use Solve Ax=b (A=Z, b=V)</p>
          <p>Cramer's rule:  x_i = det(A_i) / det(A)</p>
          <p>Check: if |det(A)| ≈ 0, the circuit has no unique solution</p>
        </CardContent>
      </Card>
    </div>
  );
}
